import PropTypes from 'prop-types';
import * as React from 'react';

// material-ui
import { useTheme } from '@mui/material/styles';
import {
  Box,
  CardContent,
  Grid,
  InputAdornment,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  TableSortLabel,
  TextField,
  Typography,
} from '@mui/material';
import { visuallyHidden } from '@mui/utils';

// project imports

// assets
import { Icon } from '@iconify/react';
import SearchIcon from '@iconify/icons-carbon/search';

import { createTheme, ThemeProvider } from '@mui/material/styles';

// third-party
import { useIntl } from 'react-intl';

// table sort
function descendingComparator(a, b, orderBy) {
  if (b[orderBy] < a[orderBy]) {
    return -1;
  }
  if (b[orderBy] > a[orderBy]) {
    return 1;
  }
  return 0;
}

const getComparator = (order, orderBy) =>
  order === 'desc'
    ? (a, b) => descendingComparator(a, b, orderBy)
    : (a, b) => -descendingComparator(a, b, orderBy);

function stableSort(array, comparator) {
  const stabilizedThis = array.map((el, index) => [el, index]);
  stabilizedThis.sort((a, b) => {
    const order = comparator(a[0], b[0]);
    if (order !== 0) return order;
    return a[1] - b[1];
  });
  return stabilizedThis.map((el) => el[0]);
}

const sampleData = [
  {
    StudentText: '112749 - 陳小明 @90000002 #smchan1@abc.com',
    StudentCode: '112749',
    Email: 'smchan1@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '90000002',
    FirstName: 'Chan Siu Ming',
    LastName: '陳小明',
    Gender: 'M',
    DOB: '1990-10-09T00:00:00.000Z',
    Address: 'Room 2001, Happy Garden',
    Address1: null,
    Address2: null,
    SchoolName: 'Great School',
    Form: '4',
    Class: null,
    CreateDate: '2022-06-15T08:37:01.567Z',
    CreateBy: 'U0001',
    ModifyDate: '2023-01-04T08:22:11.050Z',
    ModifyBy: 'U0001',
    EmergencyContactNo1: 'Chan Siu Siu',
    EmergencyContactPerson1: '90000000',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2023-04-12T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: '332b96ec-d729-4faf-a3cf-6500f7722038',
    FirebaseToken: null,
    MobileLoginToken:
      "j\u0001h\u0001j\u0001k\u0001h\u0001k\u0001j\u0001H\u0001h\u0001B\u0001G\u0001'\u0002E\u0001)\u0002J\u0001(\u0002K\u0001*\u0002+\u0002-\u0002+\u0002\u0017\u0003\u001f\u0003\u001f\u0003V\u0001Y\u0001W\u0001.\u00025\u00029\u0002.\u0002{\u0003L\u0001a\u0001T\u00013\u0002T\u0001T\u0001\r\u0003\u0014\u0003U\u0001\\\u0001_\u0001Y\u0001\u0001\\\u0001\r\u0002j\u0001o\u0001%\u0002t\u0001\u0002\u0002\t\u0002\u0002\u00036\u0003\u0007\u0004'\u0005b\u0005",
    Area: null,
    District: null,
    AppSound: true,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112750 - 楊瑩瑩 @90000003 #YYYeung@abc.com',
    StudentCode: '112750',
    Email: 'YYYeung@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '90000003',
    FirstName: 'Yeung Ying Ying',
    LastName: '楊瑩瑩',
    Gender: 'F',
    DOB: '1999-03-10T00:00:00.000Z',
    Address: 'Room 2202, Yui On House',
    Address1: null,
    Address2: null,
    SchoolName: 'Green School',
    Form: '1',
    Class: null,
    CreateDate: '2022-06-15T09:55:05.643Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'Yeung Ming',
    EmergencyContactPerson1: '90000004',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2022-10-26T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: '52731e4e-4aca-48c0-822a-f302527a00ab',
    FirebaseToken: null,
    MobileLoginToken:
      'j\u0001h\u0001j\u0001j\u0001h\u0001C\u0001i\u0001E\u0001i\u0001F\u0001D\u0001C\u0001D\u0001H\u0001J\u0001(\u0002+\u0002I\u0001,\u0002(\u0002.\u0002\u0017\u0003.\u00023\u00020\u0002,\u0002W\u0001\\\u00010\u00026\u0002.\u00027\u0002O\u00015\u0002L\u00013\u0002T\u0001\\\u0004\\\u0004V\u0001U\u0001[\u0001v\u0001\\\u0001"\u0006\\\u0001\n\u0002\u0015\u0002q\u0001u\u0001t\u0001\n\u0002[\u0002\u0017\u0002F\u0002w\u0002:\u0005\n\t',
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: null,
  },
  {
    StudentText: '112751 - 劉志明 @90000005 #lming@abc.com',
    StudentCode: '112751',
    Email: 'lming@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '90000005',
    FirstName: 'Lau Chi Ming',
    LastName: '劉志明',
    Gender: 'M',
    DOB: '2010-03-11T00:00:00.000Z',
    Address: 'Room 1104, Tai On House.',
    Address1: null,
    Address2: null,
    SchoolName: 'Green School',
    Form: '4',
    Class: null,
    CreateDate: '2022-06-16T02:27:33.047Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'Lau Chi Wing',
    EmergencyContactPerson1: '90000006',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2023-03-24T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: null,
  },
  {
    StudentText: '112752 - hi @93145367 #frankieyueee@gmail.com',
    StudentCode: '112752',
    Email: 'frankieyueee@gmail.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '93145367',
    FirstName: 'Yue Ho Yin',
    LastName: 'hi',
    Gender: 'M',
    DOB: '2022-06-08T00:00:00.000Z',
    Address: 'Tsuen Wan',
    Address1: null,
    Address2: null,
    SchoolName: 'HKMA ',
    Form: 'F3',
    Class: null,
    CreateDate: '2022-06-16T02:30:25.563Z',
    CreateBy: 'U0001',
    ModifyDate: '2023-03-15T09:36:04.053Z',
    ModifyBy: 'U0001',
    EmergencyContactNo1: 'leo cheng',
    EmergencyContactPerson1: '999',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: 'CCBC-CC',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2022-06-30T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: '0da681b1-1f31-4dfc-bcd4-c2a36b02ab83',
    FirebaseToken: null,
    MobileLoginToken:
      "j\u0001h\u0001j\u0001j\u0001h\u0001C\u0001i\u0001E\u0001i\u0001I\u0001D\u0001K\u0001D\u0001G\u0001(\u0002J\u0001I\u0001*\u0002'\u0002.\u0002+\u0002\u0017\u0003/\u0002.\u0002V\u0001\"\u0003[\u00013\u00023\u00027\u0002.\u0002w\u0003M\u0001~\u0003S\u00013\u0002T\u0001S\u0001\u0013\u0003p\u0001U\u0001\\\u0001^\u0001p\u0003r\u0003\\\u0001i\u0001g\u0001n\u0001m\u0001x\u0001G\u0002\t\u0002\u0002\u0003+\u0003w\u0002'\u0005\u0014\t",
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112753 - 陳嘉茵 @91234567 #kychan@abc.com',
    StudentCode: '112753',
    Email: 'kychan@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '91234567',
    FirstName: 'Chan Ka Yan',
    LastName: '陳嘉茵',
    Gender: 'F',
    DOB: '2009-04-04T00:00:00.000Z',
    Address: 'Room 222, Yue Tai House',
    Address1: null,
    Address2: null,
    SchoolName: 'Green School',
    Form: '1',
    Class: null,
    CreateDate: '2022-06-16T02:32:04.097Z',
    CreateBy: 'U0001',
    ModifyDate: '2023-02-28T02:53:04.683Z',
    ModifyBy: 'U0001',
    EmergencyContactNo1: 'Chan Siu Ming',
    EmergencyContactPerson1: '91231234',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2023-03-30T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112754 - 黃志恒 @93000001 #chwong@abc.com',
    StudentCode: '112754',
    Email: 'chwong@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '93000001',
    FirstName: 'Wong Chi Hang',
    LastName: '黃志恒',
    Gender: 'M',
    DOB: '2009-11-11T00:00:00.000Z',
    Address: 'Room 1309, Happy Building',
    Address1: null,
    Address2: null,
    SchoolName: 'Green School',
    Form: '4',
    Class: null,
    CreateDate: '2022-06-16T04:43:20.193Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'Wong Wai',
    EmergencyContactPerson1: '93000002',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2022-12-15T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: null,
  },
  {
    StudentText: '112755 - 李玲玲 @98764321 #lllee@abc.com',
    StudentCode: '112755',
    Email: 'lllee@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '98764321',
    FirstName: 'Lee Ling Ling',
    LastName: '李玲玲',
    Gender: 'F',
    DOB: '2010-09-22T00:00:00.000Z',
    Address: 'Room 2A, Grand Garden',
    Address1: null,
    Address2: null,
    SchoolName: 'Green School',
    Form: '1',
    Class: null,
    CreateDate: '2022-06-16T07:10:06.397Z',
    CreateBy: 'U0001',
    ModifyDate: '2023-02-28T03:58:18.130Z',
    ModifyBy: 'U0001',
    EmergencyContactNo1: 'Lee To',
    EmergencyContactPerson1: '98764322',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2022-06-30T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112756 - 郭鳳玲 @98000001 #jkwok@abc.com',
    StudentCode: '112756',
    Email: 'jkwok@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '98000001',
    FirstName: 'Kwok Fung Ling',
    LastName: '郭鳳玲',
    Gender: 'F',
    DOB: '2010-08-19T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: 'Green School',
    Form: '2',
    Class: null,
    CreateDate: '2022-06-16T07:34:46.723Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'Kwok Siu Ka',
    EmergencyContactPerson1: '98000002',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2023-02-17T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: null,
  },
  {
    StudentText: '112757 - Yue @93145555 #frankie@yahoo.com',
    StudentCode: '112757',
    Email: 'frankie@yahoo.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '93145555',
    FirstName: 'Frankie ',
    LastName: 'Yue',
    Gender: 'M',
    DOB: '2022-06-09T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: 'HKMA',
    Form: 'F4',
    Class: null,
    CreateDate: '2022-06-17T03:58:06.970Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2023-04-12T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: null,
  },
  {
    StudentText: '112758 - m @123456 #111@111.com',
    StudentCode: '112758',
    Email: '111@111.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '123456',
    FirstName: 'mic',
    LastName: 'm',
    Gender: 'M',
    DOB: '2022-06-23T00:00:00.000Z',
    Address: '123456',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2022-06-21T04:38:23.267Z',
    CreateBy: 'U0001',
    ModifyDate: '2022-06-21T04:41:29.573Z',
    ModifyBy: 'U0001',
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2022-10-06T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: 'TEST 3',
  },
  {
    StudentText: '112759 - Chan @98899000 #rrrr@yahoo.com',
    StudentCode: '112759',
    Email: 'rrrr@yahoo.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '98899000',
    FirstName: 'Leo ',
    LastName: 'Chan',
    Gender: 'M',
    DOB: '2022-03-10T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2022-06-28T02:50:32.360Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2022-06-30T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112760 - 張偉 @91111111 #CW@abc.com',
    StudentCode: '112760',
    Email: 'CW@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '91111111',
    FirstName: 'Cheung  Wai',
    LastName: '張偉',
    Gender: 'M',
    DOB: '2011-07-14T00:00:00.000Z',
    Address: 'Room 2232',
    Address1: null,
    Address2: null,
    SchoolName: 'Green School',
    Form: '1',
    Class: null,
    CreateDate: '2022-06-29T09:03:52.340Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'Cheung Ming (Father)',
    EmergencyContactPerson1: '92222222',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: 'Testing',
  },
  {
    StudentText: '112761 -  @ #Superbon@gmail.com',
    StudentCode: '112761',
    Email: 'Superbon@gmail.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '',
    FirstName: 'Superbon',
    LastName: '',
    Gender: 'M',
    DOB: '2022-06-30T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2022-06-30T02:27:15.223Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2022-06-30T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112762 - Yue @87778999 #yyyy@yahoo.cpm',
    StudentCode: '112762',
    Email: 'yyyy@yahoo.cpm',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '87778999',
    FirstName: 'Frankie ',
    LastName: 'Yue',
    Gender: 'M',
    DOB: '2022-06-02T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2022-06-30T03:28:22.907Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: '2022-06-30T00:00:00.000Z',
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112763 -  @87778999 #',
    StudentCode: '112763',
    Email: '',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '87778999',
    FirstName: 'Maisy',
    LastName: '',
    Gender: 'F',
    DOB: '2022-06-16T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2022-06-30T03:29:16.813Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112764 -  @ #',
    StudentCode: '112764',
    Email: '',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '',
    FirstName: 'Larry',
    LastName: '',
    Gender: 'F',
    DOB: '1900-01-01T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2022-07-07T07:34:27.537Z',
    CreateBy: 'U0033',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112765 - 陳小明 @61382899 #ochan@apex.hk',
    StudentCode: '112765',
    Email: 'ochan@apex.hk',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '61382899',
    FirstName: 'Ophe',
    LastName: '陳小明',
    Gender: 'F',
    DOB: '2009-07-03T00:00:00.000Z',
    Address: 'Hong Kong',
    Address1: null,
    Address2: null,
    SchoolName: 'ABC schoo;',
    Form: 'Primary',
    Class: null,
    CreateDate: '2022-07-08T02:00:20.967Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'Cani',
    EmergencyContactPerson1: '98151755',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: 'Test',
  },
  {
    StudentText: '112766 - Chan Wing Chi @61382899 #sss@ss.com',
    StudentCode: '112766',
    Email: 'sss@ss.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '61382899',
    FirstName: 'Chan Wing Chi',
    LastName: 'Chan Wing Chi',
    Gender: 'F',
    DOB: '2022-10-13T00:00:00.000Z',
    Address: 'Hong kong',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2022-10-07T07:41:25.707Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '222222222',
    EmergencyContactPerson1: '222222222',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112767 - 陳比利 @23454666 #billychan@doclever.hk',
    StudentCode: '112767',
    Email: 'billychan@doclever.hk',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '23454666',
    FirstName: 'Billy Chan',
    LastName: '陳比利',
    Gender: 'F',
    DOB: '2004-07-29T00:00:00.000Z',
    Address: 'Shatin',
    Address1: null,
    Address2: null,
    SchoolName: 'Happy School',
    Form: 'S6',
    Class: null,
    CreateDate: '2022-10-21T08:35:03.187Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'Chan Man',
    EmergencyContactPerson1: '31346545',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112768 -  @ #',
    StudentCode: '112768',
    Email: '',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '',
    FirstName: 'Franfranfran',
    LastName: '',
    Gender: 'F',
    DOB: '1900-01-01T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2022-11-07T09:09:31.497Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '*',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112778 - 陳 @12345678 #ken@gmail.com',
    StudentCode: '112778',
    Email: 'ken@gmail.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '12345678',
    FirstName: 'Kenny',
    LastName: '陳',
    Gender: 'M',
    DOB: '2023-01-01T00:00:00.000Z',
    Address: 'Kwun Tong',
    Address1: null,
    Address2: null,
    SchoolName: 'DMS',
    Form: '5',
    Class: null,
    CreateDate: '2023-01-12T08:01:44.033Z',
    CreateBy: 'U0001',
    ModifyDate: '2023-01-12T09:56:32.250Z',
    ModifyBy: 'U0001',
    EmergencyContactNo1: 'Ken',
    EmergencyContactPerson1: '32165487',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: 'CCBC-CC,CCBC-CEC',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: 'Halo',
  },
  {
    StudentText: '112779 - 陳 @12365487 #messi@gmail.com',
    StudentCode: '112779',
    Email: 'messi@gmail.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '12365487',
    FirstName: 'Leo',
    LastName: '陳',
    Gender: 'M',
    DOB: '2023-01-02T00:00:00.000Z',
    Address: 'Paris',
    Address1: null,
    Address2: null,
    SchoolName: 'BCN SCHOOL',
    Form: '7',
    Class: null,
    CreateDate: '2023-01-12T08:02:52.907Z',
    CreateBy: 'U0001',
    ModifyDate: '2023-03-23T02:14:47.983Z',
    ModifyBy: 'U0001',
    EmergencyContactNo1: 'Georg',
    EmergencyContactPerson1: '23564781',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: 'CCBC-CC,CCBC-CEC',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: 'Halo',
  },
  {
    StudentText: '112781 -  @91000001 #student01@abc.com',
    StudentCode: '112781',
    Email: 'student01@abc.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '91000001',
    FirstName: 'Student01',
    LastName: '',
    Gender: 'M',
    DOB: '2023-02-02T00:00:00.000Z',
    Address: '901',
    Address1: null,
    Address2: null,
    SchoolName: 'High School',
    Form: 'F1',
    Class: null,
    CreateDate: '2023-02-02T05:02:49.767Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: 'CCBC-CC',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112782 - Test @12345678 #testing@apex.com',
    StudentCode: '112782',
    Email: 'testing@apex.com',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '12345678',
    FirstName: 'Jim',
    LastName: 'Test',
    Gender: 'M',
    DOB: '2023-01-04T00:00:00.000Z',
    Address: 'abcdefg',
    Address1: null,
    Address2: null,
    SchoolName: 'DMS',
    Form: '6',
    Class: null,
    CreateDate: '2023-02-02T05:06:03.743Z',
    CreateBy: 'U0001',
    ModifyDate: '2023-02-28T04:15:06.180Z',
    ModifyBy: 'U0001',
    EmergencyContactNo1: 'Dan',
    EmergencyContactPerson1: '65432178',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: 'CCBC-CC',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112783 -  @90000001 #',
    StudentCode: '112783',
    Email: '',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '90000001',
    FirstName: 'Larry Yeung',
    LastName: '',
    Gender: 'M',
    DOB: '2023-03-01T00:00:00.000Z',
    Address: 'Room 9001',
    Address1: null,
    Address2: null,
    SchoolName: 'Green School',
    Form: 'F1',
    Class: null,
    CreateDate: '2023-03-23T02:30:24.833Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'David Chan',
    EmergencyContactPerson1: '90000002',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: 'CCBC-CC',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112784 - 123 @23131514 #fwes',
    StudentCode: '112784',
    Email: 'fwes',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '23131514',
    FirstName: '123',
    LastName: '123',
    Gender: 'M',
    DOB: '1900-01-01T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: 'vsdv',
    Form: 'vsdvsc',
    Class: null,
    CreateDate: '2023-03-29T01:44:02.513Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: 'vsdvs',
    EmergencyContactPerson1: '12313213',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: 'F',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: 'c',
  },
  {
    StudentText: '112785 - 3123 @312 #12312',
    StudentCode: '112785',
    Email: '12312',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '312',
    FirstName: '123',
    LastName: '3123',
    Gender: 'M',
    DOB: '1900-01-01T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2023-03-29T07:54:53.807Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112786 -  @ #123123',
    StudentCode: '112786',
    Email: '123123',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '',
    FirstName: '123',
    LastName: '',
    Gender: 'M',
    DOB: '1900-01-01T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2023-03-29T09:50:18.380Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112787 -  @98009008 #',
    StudentCode: '112787',
    Email: '',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '98009008',
    FirstName: 'Trevor',
    LastName: '',
    Gender: 'M',
    DOB: '1900-01-01T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2023-03-31T03:40:32.743Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
  {
    StudentText: '112788 -  @98891555 #',
    StudentCode: '112788',
    Email: '',
    Password: '1\u0002Y\u0002*\u0003\u001c\u0005',
    Mobile: '98891555',
    FirstName: 'Johnny',
    LastName: '',
    Gender: 'M',
    DOB: '1900-01-01T00:00:00.000Z',
    Address: '',
    Address1: null,
    Address2: null,
    SchoolName: '',
    Form: '',
    Class: null,
    CreateDate: '2023-04-12T08:07:07.673Z',
    CreateBy: 'U0001',
    ModifyDate: null,
    ModifyBy: null,
    EmergencyContactNo1: '',
    EmergencyContactPerson1: '',
    EmergencyContactRelation1: '',
    EmergencyContactNo2: '',
    EmergencyContactPerson2: '',
    EmergencyContactRelation2: '',
    Active: true,
    BranchCode: '',
    Pin: null,
    PinTime: null,
    Status: 'Pending',
    LastInvocieDate: null,
    Paid: null,
    Collected: null,
    OneSignalID: null,
    FirebaseToken: null,
    MobileLoginToken: null,
    Area: null,
    District: null,
    AppSound: false,
    MasterCode: null,
    PrintID: null,
    Remarks: '',
  },
];

const headCells = [
  {
    id: 'StudentCode',
    numeric: true,
    label: 'code',
    align: 'left',
  },
  {
    id: 'FirstName',
    numeric: false,
    label: 'name',
    align: 'left',
  },
  {
    id: 'Email',
    numeric: true,
    label: 'email',
    align: 'left',
  },
  {
    id: 'Mobile',
    numeric: true,
    label: 'mobile',
    align: 'left',
  },
  {
    id: 'SchoolName',
    numeric: false,
    label: 'school',
    align: 'left',
  },
];

// ==============================|| TABLE HEADER ||============================== //

function EnhancedTableHead({ order, orderBy, onRequestSort }) {
  const createSortHandler = (property) => (event) => {
    onRequestSort(event, property);
  };
  const intl = useIntl();
  return (
    <TableHead>
      <TableRow>
        {headCells.map((headCell) => (
          <TableCell
            key={headCell.id}
            align={headCell.align}
            padding={headCell.disablePadding ? 'none' : 'normal'}
            sortDirection={orderBy === headCell.id ? order : false}
          >
            <TableSortLabel
              active={orderBy === headCell.id}
              direction={orderBy === headCell.id ? order : 'asc'}
              onClick={createSortHandler(headCell.id)}
            >
              {intl.formatMessage({ id: `${headCell.label}` })}
              {orderBy === headCell.id ? (
                <Box component="span" sx={visuallyHidden}>
                  {order === 'desc' ? 'sorted descending' : 'sorted ascending'}
                </Box>
              ) : null}
            </TableSortLabel>
          </TableCell>
        ))}
      </TableRow>
    </TableHead>
  );
}

EnhancedTableHead.propTypes = {
  theme: PropTypes.object,
  onRequestSort: PropTypes.func.isRequired,
  order: PropTypes.oneOf(['asc', 'desc']).isRequired,
  orderBy: PropTypes.string.isRequired,
  rowCount: PropTypes.number.isRequired,
};

// ==============================|| Schedules (List) ||============================== //

const GetStudentContent = ({ setStudentInfo, handleClose }) => {
  const theme = useTheme();
  // const dispatch = useDispatch();
  const [order, setOrder] = React.useState('asc');
  const [orderBy, setOrderBy] = React.useState('calories');
  const [page, setPage] = React.useState(0);
  const [rowsPerPage, setRowsPerPage] = React.useState(5);
  const [search, setSearch] = React.useState('');
  const [rows, setRows] = React.useState([]);
  const [holdRowData, setHoldRowData] = React.useState([]);
  const intl = useIntl();

  React.useEffect(() => {
    setRows([...sampleData]);
    setHoldRowData([...sampleData]);
  }, []);

  const themeTypo = createTheme({
    typography: {
      fontSize: '13',
      padding: '15px',
    },
    components: {
      MuiTypography: {
        styleOverrides: { root: { padding: '6px' } },
      },
    },
  });

  const handleSearch = (event) => {
    const newString = event?.target.value;
    setSearch(newString || '');

    if (newString) {
      const newRows = rows.filter((row) => {
        let matches = true;

        const properties = ['StudentCode', 'FirstName', 'Email', 'Mobile', 'SchoolName'];
        let containsQuery = false;

        properties.forEach((property) => {
          if (row[property].toString().toLowerCase().includes(newString.toString().toLowerCase())) {
            containsQuery = true;
          }
        });

        if (!containsQuery) {
          matches = false;
        }
        return matches;
      });
      setRows(newRows);
    } else {
      setRows(holdRowData);
    }
  };

  const handleRequestSort = (event, property) => {
    const isAsc = orderBy === property && order === 'asc';
    setOrder(isAsc ? 'desc' : 'asc');
    setOrderBy(property);
  };

  const handleChangePage = (event, newPage) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event?.target.value, 10));
    setPage(0);
  };

  const emptyRows = page > 0 ? Math.max(0, (1 + page) * rowsPerPage - rows.length) : 0;

  return (
    <Box>
      <CardContent>
        <Grid container justifyContent="space-between" alignItems="center" spacing={2}>
          <Grid item xs={12} sm={6}>
            <TextField
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <Icon icon={SearchIcon} />
                  </InputAdornment>
                ),
              }}
              onChange={handleSearch}
              placeholder=""
              value={search}
              size="small"
            />
          </Grid>
        </Grid>
      </CardContent>

      {/* table */}
      <ThemeProvider theme={themeTypo}>
        <TableContainer>
          <Table sx={{ minWidth: 750 }} aria-labelledby="tableTitle">
            <EnhancedTableHead
              order={order}
              orderBy={orderBy}
              onRequestSort={handleRequestSort}
              rowCount={rows.length}
              theme={theme}
            />
            <TableBody>
              {rows
                .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                .map((row, index) => {
                  /** Make sure no display bugs if row isn't an OrderData object */
                  if (typeof row === 'number') return null;

                  {
                    /* const isItemSelected = isSelected(row.name); */
                  }
                  const labelId = `enhanced-table-checkbox-${index}`;

                  return (
                    <TableRow
                      onClick={() => {
                        setStudentInfo((prevState) => ({
                          ...prevState,
                          code: row.StudentCode,
                          name: `${row.FirstName} - ${row.LastName} - ${row.Mobile}`,
                        }));
                        handleClose();
                      }}
                      role="checkbox"
                      tabIndex={-1}
                      key={index}
                      sx={{ cursor: 'pointer' }}
                    >
                      <TableCell component="th" id={labelId} scope="row" size="small">
                        <Typography>{row.StudentCode} </Typography>
                      </TableCell>
                      <TableCell
                        component="th"
                        id={labelId}
                        scope="row"
                        // onClick={(event) => handleClick(event, row.name)}
                        sx={{ cursor: 'pointer' }}
                        size="small"
                      >
                        <Typography> {`${row.FirstName} ${row.LastName}`} </Typography>
                      </TableCell>
                      <TableCell size="small">
                        <Typography>{row.Email}</Typography>
                      </TableCell>
                      <TableCell size="small">
                        <Typography>{row.Mobile}</Typography>
                      </TableCell>
                      <TableCell align="left" size="small">
                        <Typography>{row.SchoolName}</Typography>
                      </TableCell>
                    </TableRow>
                  );
                })}
              {emptyRows > 0 && (
                <TableRow
                  style={{
                    height: 53 * emptyRows,
                  }}
                >
                  <TableCell colSpan={6} />
                </TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>
      </ThemeProvider>

      {/* table pagination */}
      <TablePagination
        rowsPerPageOptions={[5, 10]}
        component="div"
        count={rows.length}
        rowsPerPage={rowsPerPage}
        page={page}
        onPageChange={handleChangePage}
        onRowsPerPageChange={handleChangeRowsPerPage}
        labelRowsPerPage={intl.formatMessage({ id: 'Show' })}
      />
    </Box>
  );
};

export default GetStudentContent;
